# Generated by Django 3.2.9 on 2023-01-29 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.CharField(blank=True, max_length=2000, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to='')),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
    ]
