# Generated by Django 3.2.9 on 2022-11-22 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quiz', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_taker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.parentquiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='field',
            field=models.ManyToManyField(blank=True, to='quiz.ParentField'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.ForeignKey(blank=True, max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.questiontype'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='quiz.quiz'),
        ),
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.ManyToManyField(blank=True, to='quiz.ParentStatus'),
        ),
        migrations.AddField(
            model_name='parentstatus',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.parentquiz'),
        ),
        migrations.AddField(
            model_name='parentfield',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.parentquiz'),
        ),
        migrations.AddField(
            model_name='parentfield',
            name='parent_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.parentstatus'),
        ),
        migrations.AddField(
            model_name='myquiz',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_quiz', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='myquestion',
            name='my_quiz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_question', to='quiz.myquiz'),
        ),
        migrations.AddField(
            model_name='myquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_question', to='quiz.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='quiz.question'),
        ),
    ]
