# Generated by Django 3.2.9 on 2022-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(max_length=200)),
                ('actualErrorName', models.CharField(blank=True, max_length=100, null=True)),
                ('actualErrorMessage', models.CharField(blank=True, max_length=200, null=True)),
                ('checked', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
