# Generated by Django 3.2.9 on 2022-12-23 05:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20221221_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_taken_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
