# Generated by Django 3.2.9 on 2022-12-26 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_test_taken_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_offset',
            field=models.IntegerField(default=0),
        ),
    ]
