# Generated by Django 3.2.9 on 2023-01-25 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_date_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sns_thumbnail',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
