# Generated by Django 3.2.9 on 2022-11-22 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('best', models.BooleanField(null=True)),
                ('on_reply', models.BooleanField(default=False)),
                ('good', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='BoardAnswerLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BoardCenterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=200)),
                ('used_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BoardParentCenterTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_tag', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BoardQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=400)),
                ('slug', models.SlugField()),
                ('solved', models.BooleanField(default=False)),
                ('post_on_going', models.BooleanField(default=True)),
                ('select_best_on_going', models.BooleanField(default=False)),
                ('vote_on_going', models.BooleanField(default=False)),
                ('on_answer', models.BooleanField(default=False)),
                ('on_reply', models.BooleanField(default=False)),
                ('vote', models.IntegerField(default=0)),
                ('img', models.ImageField(blank=True, null=True, upload_to='')),
                ('viewed', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='BoardQuestionLiked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='BoardReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='BoardUserTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_num', models.IntegerField(default=0)),
                ('viewed_num', models.IntegerField(default=0)),
                ('total_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavoriteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ManyToManyField(related_name='favorite_question', to='board.BoardQuestion')),
            ],
        ),
    ]
