# Generated by Django 3.2.9 on 2022-11-22 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('board', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userfavoritequestion',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='favorite_question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardusertag',
            name='tag',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='board.boardcentertag'),
        ),
        migrations.AddField(
            model_name='boardusertag',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_tag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardreply',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='board.boardanswer'),
        ),
        migrations.AddField(
            model_name='boardreply',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardquestionliked',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='liked_num', to='board.boardquestion'),
        ),
        migrations.AddField(
            model_name='boardquestionliked',
            name='user',
            field=models.ManyToManyField(default=None, related_name='liked_num', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardquestion',
            name='tag',
            field=models.ManyToManyField(related_name='question', to='board.BoardCenterTag'),
        ),
        migrations.AddField(
            model_name='boardquestion',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardcentertag',
            name='parent_tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='center_tag', to='board.boardparentcentertag'),
        ),
        migrations.AddField(
            model_name='boardcentertag',
            name='user',
            field=models.ManyToManyField(blank=True, default=None, related_name='center_tag', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardanswerliked',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='liked_answer', to='board.boardanswer'),
        ),
        migrations.AddField(
            model_name='boardanswerliked',
            name='user',
            field=models.ManyToManyField(default=None, related_name='liked_answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='board.boardquestion'),
        ),
        migrations.AddField(
            model_name='boardanswer',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
