# Generated by Django 3.2.9 on 2023-01-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardquestion',
            name='post_on_going',
        ),
        migrations.RemoveField(
            model_name='boardquestion',
            name='select_best_on_going',
        ),
        migrations.RemoveField(
            model_name='boardquestion',
            name='vote',
        ),
        migrations.RemoveField(
            model_name='boardquestion',
            name='vote_on_going',
        ),
        migrations.AddField(
            model_name='boardquestion',
            name='comment_to_respondents',
            field=models.CharField(default='', max_length=100),
        ),
    ]
