# Generated by Django 3.2.9 on 2023-01-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20230110_0129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcentertag',
            name='user',
        ),
        migrations.AlterField(
            model_name='boardquestion',
            name='comment_to_respondents',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
