# Generated by Django 3.2.9 on 2023-01-16 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_boardanswer_on_best'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardquestion',
            name='on_best',
        ),
    ]
