# Generated by Django 3.2.9 on 2023-02-24 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0008_alter_boardusertag_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardquestion',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
