# Generated by Django 3.2.9 on 2023-03-15 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0009_alter_boardquestion_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='EachFavoriteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='each_question', to='board.boardquestion')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='each_question', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userfavoritequestion',
            name='question',
            field=models.ManyToManyField(blank=True, default=None, related_name='favorite_question', to='board.EachFavoriteQuestion'),
        ),
    ]
